# Generated by Django 4.1.5 on 2023-03-20 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekozumi_app', '0003_alter_pet_lastfed_alter_pet_pettype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='lastFed',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 17, 56, 18, 64041, tzinfo=datetime.timezone.utc)),
        ),
    ]
