# Generated by Django 4.1.5 on 2023-03-20 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekozumi_app', '0004_alter_pet_lastfed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megaboss',
            name='playerIntroDialogue',
        ),
        migrations.RemoveField(
            model_name='megaboss',
            name='playerOutroDialogue',
        ),
        migrations.AlterField(
            model_name='pet',
            name='lastFed',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 18, 26, 8, 185413, tzinfo=datetime.timezone.utc)),
        ),
    ]
